# Generated by Django 5.0.2 on 2024-02-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=400, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=400, null=True, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=400, null=True, verbose_name='Здание')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('level', models.SmallIntegerField(blank=True, null=True, verbose_name='Уровень поставщика')),
                ('who_is_the_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('-created_at',),
            },
        ),
    ]
